ALTER TABLE Treatment DROP CONSTRAINT FK_Treatment_PATIENT_ID
ALTER TABLE Treatment DROP CONSTRAINT FK_Treatment_PROVIDERS_ID
ALTER TABLE DrugTreatment DROP CONSTRAINT FK_DrugTreatment_ID
ALTER TABLE Provider DROP CONSTRAINT FK_Provider_PATIENT_ID
ALTER TABLE Radiology DROP CONSTRAINT FK_Radiology_ID
ALTER TABLE Surgery DROP CONSTRAINT FK_Surgery_ID
ALTER TABLE Radiology_date DROP CONSTRAINT FK_Radiology_date_Radiology_RID
DROP TABLE Patient CASCADE
DROP TABLE Treatment CASCADE
DROP TABLE DrugTreatment CASCADE
DROP TABLE Provider CASCADE
DROP TABLE Radiology CASCADE
DROP TABLE Surgery CASCADE
DROP TABLE Radiology_date CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
