//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.10-b140802.1033 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.30 at 10:07:54 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://cs548.stevens.edu/clinic/service/dto/util")
package edu.stevens.cs548.clinic.service.dto.util;
